require("plugins")
require("base")
require("keymaps")
require("colorscheme")
require("airline")
require("fzf")
require("cmp_lsp")
require("treesitter")
-- require("iron")
require("comment_setting")
require("vfiler_setting")
require("snippy_setting")
require("hop_setting")
require("toggleterm_setting")

